# ------------------------------------------------------------------------------
# helium server configuration
server:
  host: 0.0.0.0
  port: 8080
  redis_url: redis://helium-redis:6379
  client_max_size: 104857600 # 100 MB
# ------------------------------------------------------------------------------
# helium storage configuration
storage:
  directory: /data/helium
  generaptor:
    cache: /data/generaptor/cache
    config: /data/generaptor/config
# ------------------------------------------------------------------------------
# fusion auth api configuration
auth_api:
  backend:
    strategy: basic
    basic:
      groups: []
      users:
        - username: test
          digest: argon2-digest-goes-here
          groups:
            - DFIR
    keycloak:
      url: https://keycloak.domain.lan
      client_id: helium
      realm_name: master
      client_secret: replace-me-with-a-secret
      redirect_uri: https://helium.domain.lan/login
      include_auth: true
      verify: false
  clients: []
  iron_key: null
  can_delete_acs: []
# ------------------------------------------------------------------------------
# fusion case api configuration
case_api: {}
# ------------------------------------------------------------------------------
# fusion info api configuration
info_api:
  auth_required: false
# ------------------------------------------------------------------------------
# fusion event api configuration
event_api:
  webhook: https://n8n.domain.lan/webhook/helium
  api_key: api-key-placeholder
  api_ssl: false
  timeout: 5
# ------------------------------------------------------------------------------
# fusion constant api configuration
constant_api:
  auth_required: true
  constant_path: /conf/constant.yml
# ------------------------------------------------------------------------------
# fusion download api configuration
download_api:
  max_pending_download: 25
# ------------------------------------------------------------------------------
# synchronizer configuration
synchronizer:
  directory: /syncfs
# ------------------------------------------------------------------------------
# analyzer configuration
analyzer:
  # ----------------------------------------------------------------------------
  # hayabusa configuration
  hayabusa:
    enabled: false
    workers: 1
    program: /analyzer/hayabusa/hayabusa
    rules_dir: /analyzer/hayabusa/rules
  # ----------------------------------------------------------------------------
  # plasma configuration
  plasma:
    enabled: false
    workers: 1
    program: /analyzer/plasma/plasma
  # ----------------------------------------------------------------------------
  # plaso configuration
  plaso:
    enabled: false
    workers: 1
    program: /analyzer/plaso/log2timeline
  # ----------------------------------------------------------------------------
  # yara configuration
  yara:
    enabled: false
    workers: 1
    program: /analyzer/yara/yara
    compiled: false
    rule_files:
      - /analyzer/yara/rules/index.yar
  # ----------------------------------------------------------------------------
  # extractor configuration
  extractor:
    enabled: false
    workers: 1
